### ISSUE TITLE
Build fails when installing via Homebrew

### ISSUE THREAD

**Issue by pklaus** [Cyrex/cartool#1]
I'm on 11.1 Big Sur:

```
philipp@lion:~$ brew tap cyrex/formulae
Updating Homebrew...
==> Auto-updated Homebrew!
Updated Homebrew from fa0dd54f3 to 5e1c2cfac.
Updated 3 taps (homebrew/cask-versions, homebrew/core and homebrew/cask).
==> New Formulae
mpdecimal
==> Updated Formulae
Updated 16 formulae.
==> New Casks
digital
==> Updated Casks
Updated 110 casks.
==> Deleted Casks
oni

==> Homebrew was updated to version 2.7.7
The changelog can be found at:
  https://github.com/Homebrew/brew/releases/tag/2.7.7
==> Tapping cyrex/formulae
Cloning into '/usr/local/Homebrew/Library/Taps/cyrex/homebrew-formulae'...
remote: Enumerating objects: 10, done.
remote: Counting objects: 100% (10/10), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 19 (delta 2), reused 8 (delta 2), pack-reused 9
Receiving objects: 100% (19/19), 6.76 KiB | 2.25 MiB/s, done.
Resolving deltas: 100% (4/4), done.
Tapped 1 formula (29 files, 38KB).


philipp@lion:~$ brew install cartool
==> Installing cartool from cyrex/formulae
==> Downloading https://github.com/cyrex/cartool/archive/v0.1.0.tar.gz
==> Downloading from https://codeload.github.com/szwathub/cartool/tar.gz/v0.1.0
##O#- #                                                                       
==> make install PREFIX=/usr/local/Cellar/cartool/0.1.0
Last 15 lines from /Users/pklaus/Library/Logs/Homebrew/cartool/01.make:
    cd /tmp/cartool-20210128-4123-1afhhr7/cartool-0.1.0
    clang -x objective-c-header -target arm64-apple-macos10.9 -fmessage-length\=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -std\=gnu99 -fobjc-arc -fmodules -gmodules -fmodules-cache-path\=/Users/pklaus/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -fmodules-prune-interval\=86400 -fmodules-prune-after\=345600 -fbuild-session-file\=/Users/pklaus/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror\=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -Os -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror\=return-type -Wunreachable-code -Wno-implicit-atomic-properties -Werror\=deprecated-objc-isa-usage -Wno-objc-interface-ivars -Werror\=objc-root-class -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wno-non-literal-null-conversion -Wno-objc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DNS_BLOCK_ASSERTIONS\=1 -DOBJC_OLD_DISPATCH_PROTOTYPES\=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -g -fvisibility\=hidden -Wno-sign-conversion -Winfinite-recursion -Wno-comma -Wno-block-capture-autoreleasing -Wno-strict-prototypes -Wno-semicolon-before-method-body -iquote /tmp/cartool-20210128-4123-1afhhr7/cartool-0.1.0/build/12D4e/Intermediates/cartool.build/Release/cartool.build/cartool-generated-files.hmap -I/tmp/cartool-20210128-4123-1afhhr7/cartool-0.1.0/build/12D4e/Intermediates/cartool.build/Release/cartool.build/cartool-own-target-headers.hmap -I/tmp/cartool-20210128-4123-1afhhr7/cartool-0.1.0/build/12D4e/Intermediates/cartool.build/Release/cartool.build/cartool-all-target-headers.hmap -iquote /tmp/cartool-20210128-4123-1afhhr7/cartool-0.1.0/build/12D4e/Intermediates/cartool.build/Release/cartool.build/cartool-project-headers.hmap -I/tmp/cartool-20210128-4123-1afhhr7/cartool-0.1.0/build/12D4e/Products/Release/include -I/tmp/cartool-20210128-4123-1afhhr7/cartool-0.1.0/build/12D4e/Intermediates/cartool.build/Release/cartool.build/DerivedSources-normal/arm64 -I/tmp/cartool-20210128-4123-1afhhr7/cartool-0.1.0/build/12D4e/Intermediates/cartool.build/Release/cartool.build/DerivedSources/arm64 -I/tmp/cartool-20210128-4123-1afhhr7/cartool-0.1.0/build/12D4e/Intermediates/cartool.build/Release/cartool.build/DerivedSources -F/tmp/cartool-20210128-4123-1afhhr7/cartool-0.1.0/build/12D4e/Products/Release -F/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/System/Library/PrivateFrameworks -c /tmp/cartool-20210128-4123-1afhhr7/cartool-0.1.0/cartool/cartool-Prefix.pch -MD -MT dependencies -MF /tmp/cartool-20210128-4123-1afhhr7/cartool-0.1.0/build/12D4e/Intermediates/PrecompiledHeaders/SharedPrecompiledHeaders/8650000591405075485/cartool-Prefix.pch.d -iquote /tmp/cartool-20210128-4123-1afhhr7/cartool-0.1.0/build/12D4e/Intermediates/cartool.build/Release/cartool.build/cartool-generated-files.hmap -I/tmp/cartool-20210128-4123-1afhhr7/cartool-0.1.0/build/12D4e/Intermediates/cartool.build/Release/cartool.build/cartool-own-target-headers.hmap -I/tmp/cartool-20210128-4123-1afhhr7/cartool-0.1.0/build/12D4e/Intermediates/cartool.build/Release/cartool.build/cartool-all-target-headers.hmap -iquote /tmp/cartool-20210128-4123-1afhhr7/cartool-0.1.0/build/12D4e/Intermediates/cartool.build/Release/cartool.build/cartool-project-headers.hmap -I/tmp/cartool-20210128-4123-1afhhr7/cartool-0.1.0/build/12D4e/Products/Release/include -I/tmp/cartool-20210128-4123-1afhhr7/cartool-0.1.0/build/12D4e/Intermediates/cartool.build/Release/cartool.build/DerivedSources-normal/arm64 -I/tmp/cartool-20210128-4123-1afhhr7/cartool-0.1.0/build/12D4e/Intermediates/cartool.build/Release/cartool.build/DerivedSources/arm64 -I/tmp/cartool-20210128-4123-1afhhr7/cartool-0.1.0/build/12D4e/Intermediates/cartool.build/Release/cartool.build/DerivedSources -o /tmp/cartool-20210128-4123-1afhhr7/cartool-0.1.0/build/12D4e/Intermediates/PrecompiledHeaders/SharedPrecompiledHeaders/8650000591405075485/cartool-Prefix.pch.gch --serialize-diagnostics /tmp/cartool-20210128-4123-1afhhr7/cartool-0.1.0/build/12D4e/Intermediates/PrecompiledHeaders/SharedPrecompiledHeaders/8650000591405075485/cartool-Prefix.pch.dia
clang: error: the clang compiler does not support '-march=nehalem'

ProcessPCH /tmp/cartool-20210128-4123-1afhhr7/cartool-0.1.0/build/12D4e/Intermediates/PrecompiledHeaders/SharedPrecompiledHeaders/18022109226119370559/cartool-Prefix.pch.gch /tmp/cartool-20210128-4123-1afhhr7/cartool-0.1.0/cartool/cartool-Prefix.pch normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'cartool' from project 'cartool')
    cd /tmp/cartool-20210128-4123-1afhhr7/cartool-0.1.0
    clang -x objective-c-header -target x86_64-apple-macos10.9 -fmessage-length\=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -std\=gnu99 -fobjc-arc -fmodules -gmodules -fmodules-cache-path\=/Users/pklaus/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -fmodules-prune-interval\=86400 -fmodules-prune-after\=345600 -fbuild-session-file\=/Users/pklaus/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror\=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -Os -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror\=return-type -Wunreachable-code -Wno-implicit-atomic-properties -Werror\=deprecated-objc-isa-usage -Wno-objc-interface-ivars -Werror\=objc-root-class -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wno-non-literal-null-conversion -Wno-objc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DNS_BLOCK_ASSERTIONS\=1 -DOBJC_OLD_DISPATCH_PROTOTYPES\=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -g -fvisibility\=hidden -Wno-sign-conversion -Winfinite-recursion -Wno-comma -Wno-block-capture-autoreleasing -Wno-strict-prototypes -Wno-semicolon-before-method-body -iquote /tmp/cartool-20210128-4123-1afhhr7/cartool-0.1.0/build/12D4e/Intermediates/cartool.build/Release/cartool.build/cartool-generated-files.hmap -I/tmp/cartool-20210128-4123-1afhhr7/cartool-0.1.0/build/12D4e/Intermediates/cartool.build/Release/cartool.build/cartool-own-target-headers.hmap -I/tmp/cartool-20210128-4123-1afhhr7/cartool-0.1.0/build/12D4e/Intermediates/cartool.build/Release/cartool.build/cartool-all-target-headers.hmap -iquote /tmp/cartool-20210128-4123-1afhhr7/cartool-0.1.0/build/12D4e/Intermediates/cartool.build/Release/cartool.build/cartool-project-headers.hmap -I/tmp/cartool-20210128-4123-1afhhr7/cartool-0.1.0/build/12D4e/Products/Release/include -I/tmp/cartool-20210128-4123-1afhhr7/cartool-0.1.0/build/12D4e/Intermediates/cartool.build/Release/cartool.build/DerivedSources-normal/x86_64 -I/tmp/cartool-20210128-4123-1afhhr7/cartool-0.1.0/build/12D4e/Intermediates/cartool.build/Release/cartool.build/DerivedSources/x86_64 -I/tmp/cartool-20210128-4123-1afhhr7/cartool-0.1.0/build/12D4e/Intermediates/cartool.build/Release/cartool.build/DerivedSources -F/tmp/cartool-20210128-4123-1afhhr7/cartool-0.1.0/build/12D4e/Products/Release -F/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/System/Library/PrivateFrameworks -c /tmp/cartool-20210128-4123-1afhhr7/cartool-0.1.0/cartool/cartool-Prefix.pch -MD -MT dependencies -MF /tmp/cartool-20210128-4123-1afhhr7/cartool-0.1.0/build/12D4e/Intermediates/PrecompiledHeaders/SharedPrecompiledHeaders/18022109226119370559/cartool-Prefix.pch.d -iquote /tmp/cartool-20210128-4123-1afhhr7/cartool-0.1.0/build/12D4e/Intermediates/cartool.build/Release/cartool.build/cartool-generated-files.hmap -I/tmp/cartool-20210128-4123-1afhhr7/cartool-0.1.0/build/12D4e/Intermediates/cartool.build/Release/cartool.build/cartool-own-target-headers.hmap -I/tmp/cartool-20210128-4123-1afhhr7/cartool-0.1.0/build/12D4e/Intermediates/cartool.build/Release/cartool.build/cartool-all-target-headers.hmap -iquote /tmp/cartool-20210128-4123-1afhhr7/cartool-0.1.0/build/12D4e/Intermediates/cartool.build/Release/cartool.build/cartool-project-headers.hmap -I/tmp/cartool-20210128-4123-1afhhr7/cartool-0.1.0/build/12D4e/Products/Release/include -I/tmp/cartool-20210128-4123-1afhhr7/cartool-0.1.0/build/12D4e/Intermediates/cartool.build/Release/cartool.build/DerivedSources-normal/x86_64 -I/tmp/cartool-20210128-4123-1afhhr7/cartool-0.1.0/build/12D4e/Intermediates/cartool.build/Release/cartool.build/DerivedSources/x86_64 -I/tmp/cartool-20210128-4123-1afhhr7/cartool-0.1.0/build/12D4e/Intermediates/cartool.build/Release/cartool.build/DerivedSources -o /tmp/cartool-20210128-4123-1afhhr7/cartool-0.1.0/build/12D4e/Intermediates/PrecompiledHeaders/SharedPrecompiledHeaders/18022109226119370559/cartool-Prefix.pch.gch --serialize-diagnostics /tmp/cartool-20210128-4123-1afhhr7/cartool-0.1.0/build/12D4e/Intermediates/PrecompiledHeaders/SharedPrecompiledHeaders/18022109226119370559/cartool-Prefix.pch.dia

** BUILD FAILED **


The following build commands failed:
	ProcessPCH /tmp/cartool-20210128-4123-1afhhr7/cartool-0.1.0/build/12D4e/Intermediates/PrecompiledHeaders/SharedPrecompiledHeaders/8650000591405075485/cartool-Prefix.pch.gch /tmp/cartool-20210128-4123-1afhhr7/cartool-0.1.0/cartool/cartool-Prefix.pch normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
make: *** [build] Error 65

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/cyrex/homebrew-formulae/issues

Traceback (most recent call last):
	22: from /usr/local/Homebrew/Library/Homebrew/build.rb:227:in `<main>'
	21: from /usr/local/Homebrew/Library/Homebrew/build.rb:134:in `install'
	20: from /usr/local/Homebrew/Library/Homebrew/utils.rb:530:in `with_env'
	19: from /usr/local/Homebrew/Library/Homebrew/build.rb:139:in `block in install'
	18: from /usr/local/Homebrew/Library/Homebrew/formula.rb:1215:in `brew'
	17: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2236:in `stage'
	16: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `stage'
	15: from /usr/local/Homebrew/Library/Homebrew/resource.rb:91:in `stage'
	14: from /usr/local/Homebrew/Library/Homebrew/resource.rb:116:in `unpack'
	13: from /usr/local/Homebrew/Library/Homebrew/resource.rb:197:in `mktemp'
	12: from /usr/local/Homebrew/Library/Homebrew/mktemp.rb:63:in `run'
	11: from /usr/local/Homebrew/Library/Homebrew/mktemp.rb:63:in `chdir'
	10: from /usr/local/Homebrew/Library/Homebrew/mktemp.rb:63:in `block in run'
	 9: from /usr/local/Homebrew/Library/Homebrew/resource.rb:121:in `block in unpack'
	 8: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2256:in `block in stage'
	 7: from /usr/local/Homebrew/Library/Homebrew/utils.rb:530:in `with_env'
	 6: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2257:in `block (2 levels) in stage'
	 5: from /usr/local/Homebrew/Library/Homebrew/formula.rb:1222:in `block in brew'
	 4: from /usr/local/Homebrew/Library/Homebrew/build.rb:175:in `block (2 levels) in install'
	 3: from /usr/local/Homebrew/Library/Taps/cyrex/homebrew-formulae/Formula/cartool.rb:16:in `install'
	 2: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2043:in `system'
	 1: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2043:in `open'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2107:in `block in system': Failed executing: make install PREFIX=/usr/local/Cellar/cartool/0.1.0 (BuildError)
	9: from /usr/local/Homebrew/Library/Homebrew/brew.rb:155:in `<main>'
	8: from /usr/local/Homebrew/Library/Homebrew/brew.rb:167:in `rescue in <main>'
	7: from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:475:in `dump'
	6: from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:421:in `issues'
	5: from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:425:in `fetch_issues'
	4: from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:324:in `issues_for_formula'
	3: from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:305:in `search_issues'
	2: from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:422:in `search'
	1: from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:230:in `open_api'
/usr/local/Homebrew/Library/Homebrew/utils/github.rb:285:in `raise_api_error': Validation Failed: [{"message"=>"The listed users and repositories cannot be searched either because the resources do not exist or you do not have permission to view them.", "resource"=>"Search", "field"=>"q", "code"=>"invalid"}] (GitHub::ValidationFailedError)

```

**Comment by seansica** [comment]
I get the same error.

```
➜xcodebuild -version
Xcode 13.2.1
Build version 13C100

➜sw_vers
ProductName:	macOS
ProductVersion:	11.6.3
BuildVersion:	20G415
```
